apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spark-ui-ingress
spec:
  rules:
  - host: spark-ui.lab.bmlldev.com
    http:
      paths:
      - path: /
        backend:
          serviceName: spark-ui-proxy
          servicePort: http
