apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zeppelin-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: spark-zeppelin.lab.bmlldev.com
    http:
      paths:
      - path: /
        backend:
          serviceName: zeppelin
          servicePort: http
